version: '3'

volumes:
  bundle:

services:
  rbexy:
    build: .
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - $HOME/.ssh:/root/.ssh:ro
      - $HOME/.gitconfig:/root/.gitconfig:ro
      - $HOME/.gem/credentials:/root/.gem/credentials
    working_dir: /app
